import type { Metadata } from 'next';
import { Lexend } from 'next/font/google';
import './globals.css';
import { cn } from '@/utils';

const lexend = Lexend({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Carbon Footprint Explorer',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const RootLayout = ({ children }: Readonly<Props>): JSX.Element => {
  return (
    <html lang='en'>
      <body className={cn(lexend.className, 'bg-secondary')}>
        {children}
        <footer className='text-custom-white mt-auto flex justify-center pb-4 pt-8'>
          <p>
            Created with love by{' '}
            <a
              href='https://www.linkedin.com/in/muhammadanasafzal/'
              target='_blank'
              rel='noopener noreferrer'
            >
              @Muhammad Anas
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
